/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArRouteImport } from './routes/ar'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArIndexRouteImport } from './routes/ar.index'
import { Route as MediaSplatRouteImport } from './routes/media/$'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedTagsRouteImport } from './routes/_authenticated/tags'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSeoRouteImport } from './routes/_authenticated/seo'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPublishedRouteImport } from './routes/_authenticated/published'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedFeaturedRouteImport } from './routes/_authenticated/featured'
import { Route as AuthenticatedDraftsRouteImport } from './routes/_authenticated/drafts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedAuthorsRouteImport } from './routes/_authenticated/authors'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ArBlogIndexRouteImport } from './routes/ar.blog.index'
import { Route as AuthenticatedPostsIndexRouteImport } from './routes/_authenticated/posts.index'
import { Route as ArBlogSlugRouteImport } from './routes/ar.blog.$slug'
import { Route as AuthenticatedPostsNewRouteImport } from './routes/_authenticated/posts.new'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicHooksPublishLinkedinRouteImport } from './routes/api/public/hooks/publish-linkedin'
import { Route as AuthenticatedPostsIdEditRouteImport } from './routes/_authenticated/posts.$id.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArIndexRoute = ArIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArRoute,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTagsRoute = AuthenticatedTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeoRoute = AuthenticatedSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishedRoute = AuthenticatedPublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeaturedRoute = AuthenticatedFeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDraftsRoute = AuthenticatedDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuthorsRoute = AuthenticatedAuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArBlogIndexRoute = ArBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => ArRoute,
} as any)
const AuthenticatedPostsIndexRoute = AuthenticatedPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArBlogSlugRoute = ArBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => ArRoute,
} as any)
const AuthenticatedPostsNewRoute = AuthenticatedPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPublishLinkedinRoute =
  ApiPublicHooksPublishLinkedinRouteImport.update({
    id: '/api/public/hooks/publish-linkedin',
    path: '/api/public/hooks/publish-linkedin',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPostsIdEditRoute =
  AuthenticatedPostsIdEditRouteImport.update({
    id: '/posts/$id/edit',
    path: '/posts/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ar': typeof ArRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/authors': typeof AuthenticatedAuthorsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/featured': typeof AuthenticatedFeaturedRoute
  '/media': typeof AuthenticatedMediaRoute
  '/published': typeof AuthenticatedPublishedRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/seo': typeof AuthenticatedSeoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tags': typeof AuthenticatedTagsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/media/$': typeof MediaSplatRoute
  '/ar/': typeof ArIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/posts/new': typeof AuthenticatedPostsNewRoute
  '/ar/blog/$slug': typeof ArBlogSlugRoute
  '/posts/': typeof AuthenticatedPostsIndexRoute
  '/ar/blog/': typeof ArBlogIndexRoute
  '/posts/$id/edit': typeof AuthenticatedPostsIdEditRoute
  '/api/public/hooks/publish-linkedin': typeof ApiPublicHooksPublishLinkedinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/authors': typeof AuthenticatedAuthorsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/featured': typeof AuthenticatedFeaturedRoute
  '/media': typeof AuthenticatedMediaRoute
  '/published': typeof AuthenticatedPublishedRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/seo': typeof AuthenticatedSeoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tags': typeof AuthenticatedTagsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/media/$': typeof MediaSplatRoute
  '/ar': typeof ArIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/posts/new': typeof AuthenticatedPostsNewRoute
  '/ar/blog/$slug': typeof ArBlogSlugRoute
  '/posts': typeof AuthenticatedPostsIndexRoute
  '/ar/blog': typeof ArBlogIndexRoute
  '/posts/$id/edit': typeof AuthenticatedPostsIdEditRoute
  '/api/public/hooks/publish-linkedin': typeof ApiPublicHooksPublishLinkedinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/ar': typeof ArRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/authors': typeof AuthenticatedAuthorsRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/drafts': typeof AuthenticatedDraftsRoute
  '/_authenticated/featured': typeof AuthenticatedFeaturedRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/published': typeof AuthenticatedPublishedRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/seo': typeof AuthenticatedSeoRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tags': typeof AuthenticatedTagsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/media/$': typeof MediaSplatRoute
  '/ar/': typeof ArIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/posts/new': typeof AuthenticatedPostsNewRoute
  '/ar/blog/$slug': typeof ArBlogSlugRoute
  '/_authenticated/posts/': typeof AuthenticatedPostsIndexRoute
  '/ar/blog/': typeof ArBlogIndexRoute
  '/_authenticated/posts/$id/edit': typeof AuthenticatedPostsIdEditRoute
  '/api/public/hooks/publish-linkedin': typeof ApiPublicHooksPublishLinkedinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ar'
    | '/contact'
    | '/login'
    | '/mcp'
    | '/privacy-policy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/authors'
    | '/categories'
    | '/dashboard'
    | '/drafts'
    | '/featured'
    | '/media'
    | '/published'
    | '/reports'
    | '/seo'
    | '/settings'
    | '/tags'
    | '/blog/$slug'
    | '/category/$slug'
    | '/media/$'
    | '/ar/'
    | '/.mcp/invoke-tool/$tool'
    | '/posts/new'
    | '/ar/blog/$slug'
    | '/posts/'
    | '/ar/blog/'
    | '/posts/$id/edit'
    | '/api/public/hooks/publish-linkedin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/mcp'
    | '/privacy-policy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/authors'
    | '/categories'
    | '/dashboard'
    | '/drafts'
    | '/featured'
    | '/media'
    | '/published'
    | '/reports'
    | '/seo'
    | '/settings'
    | '/tags'
    | '/blog/$slug'
    | '/category/$slug'
    | '/media/$'
    | '/ar'
    | '/.mcp/invoke-tool/$tool'
    | '/posts/new'
    | '/ar/blog/$slug'
    | '/posts'
    | '/ar/blog'
    | '/posts/$id/edit'
    | '/api/public/hooks/publish-linkedin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ar'
    | '/contact'
    | '/login'
    | '/mcp'
    | '/privacy-policy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/authors'
    | '/_authenticated/categories'
    | '/_authenticated/dashboard'
    | '/_authenticated/drafts'
    | '/_authenticated/featured'
    | '/_authenticated/media'
    | '/_authenticated/published'
    | '/_authenticated/reports'
    | '/_authenticated/seo'
    | '/_authenticated/settings'
    | '/_authenticated/tags'
    | '/blog/$slug'
    | '/category/$slug'
    | '/media/$'
    | '/ar/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/posts/new'
    | '/ar/blog/$slug'
    | '/_authenticated/posts/'
    | '/ar/blog/'
    | '/_authenticated/posts/$id/edit'
    | '/api/public/hooks/publish-linkedin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArRoute: typeof ArRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  MediaSplatRoute: typeof MediaSplatRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksPublishLinkedinRoute: typeof ApiPublicHooksPublishLinkedinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/': {
      id: '/ar/'
      path: '/'
      fullPath: '/ar/'
      preLoaderRoute: typeof ArIndexRouteImport
      parentRoute: typeof ArRoute
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tags': {
      id: '/_authenticated/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedTagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seo': {
      id: '/_authenticated/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof AuthenticatedSeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/published': {
      id: '/_authenticated/published'
      path: '/published'
      fullPath: '/published'
      preLoaderRoute: typeof AuthenticatedPublishedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/featured': {
      id: '/_authenticated/featured'
      path: '/featured'
      fullPath: '/featured'
      preLoaderRoute: typeof AuthenticatedFeaturedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drafts': {
      id: '/_authenticated/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof AuthenticatedDraftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/authors': {
      id: '/_authenticated/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthenticatedAuthorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/blog/': {
      id: '/ar/blog/'
      path: '/blog'
      fullPath: '/ar/blog/'
      preLoaderRoute: typeof ArBlogIndexRouteImport
      parentRoute: typeof ArRoute
    }
    '/_authenticated/posts/': {
      id: '/_authenticated/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthenticatedPostsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ar/blog/$slug': {
      id: '/ar/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/ar/blog/$slug'
      preLoaderRoute: typeof ArBlogSlugRouteImport
      parentRoute: typeof ArRoute
    }
    '/_authenticated/posts/new': {
      id: '/_authenticated/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AuthenticatedPostsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/publish-linkedin': {
      id: '/api/public/hooks/publish-linkedin'
      path: '/api/public/hooks/publish-linkedin'
      fullPath: '/api/public/hooks/publish-linkedin'
      preLoaderRoute: typeof ApiPublicHooksPublishLinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/posts/$id/edit': {
      id: '/_authenticated/posts/$id/edit'
      path: '/posts/$id/edit'
      fullPath: '/posts/$id/edit'
      preLoaderRoute: typeof AuthenticatedPostsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuthorsRoute: typeof AuthenticatedAuthorsRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDraftsRoute: typeof AuthenticatedDraftsRoute
  AuthenticatedFeaturedRoute: typeof AuthenticatedFeaturedRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedPublishedRoute: typeof AuthenticatedPublishedRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSeoRoute: typeof AuthenticatedSeoRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTagsRoute: typeof AuthenticatedTagsRoute
  AuthenticatedPostsNewRoute: typeof AuthenticatedPostsNewRoute
  AuthenticatedPostsIndexRoute: typeof AuthenticatedPostsIndexRoute
  AuthenticatedPostsIdEditRoute: typeof AuthenticatedPostsIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuthorsRoute: AuthenticatedAuthorsRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDraftsRoute: AuthenticatedDraftsRoute,
  AuthenticatedFeaturedRoute: AuthenticatedFeaturedRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedPublishedRoute: AuthenticatedPublishedRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSeoRoute: AuthenticatedSeoRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTagsRoute: AuthenticatedTagsRoute,
  AuthenticatedPostsNewRoute: AuthenticatedPostsNewRoute,
  AuthenticatedPostsIndexRoute: AuthenticatedPostsIndexRoute,
  AuthenticatedPostsIdEditRoute: AuthenticatedPostsIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ArRouteChildren {
  ArIndexRoute: typeof ArIndexRoute
  ArBlogSlugRoute: typeof ArBlogSlugRoute
  ArBlogIndexRoute: typeof ArBlogIndexRoute
}

const ArRouteChildren: ArRouteChildren = {
  ArIndexRoute: ArIndexRoute,
  ArBlogSlugRoute: ArBlogSlugRoute,
  ArBlogIndexRoute: ArBlogIndexRoute,
}

const ArRouteWithChildren = ArRoute._addFileChildren(ArRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ArRoute: ArRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  MediaSplatRoute: MediaSplatRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksPublishLinkedinRoute: ApiPublicHooksPublishLinkedinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
